### ISSUE TITLE
Works with Omeka 2.4.1?

### ISSUE THREAD

**Issue by janetmango** [Daniel-KM/Omeka-plugin-Stats#1]
I just tried to upload the Stats plugin to my version of Omeka 2.4.1 and I got an error that it's an invalid plug-in.  I tried uploading using both FileZilla and the upload function from the webhost.  Thanks.

**Comment by Daniel-KM** [comment]
Hi,

When you download a zip from Github, the folder should be renamed, here "Stats".

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
