### ISSUE TITLE
Invalid Plugin

### ISSUE THREAD

**Issue by marcioyonamine** [Daniel-KM/Omeka-plugin-Stats#11]
I´m using Omeka 2.6.1 version, PHP 7.0 and Brazilian Portuguese version.  I can see Stats in plugin list, but can´t active it. There´s a message "Este não é um plugin válido / This is not a valid plugin".
I have no idea what to do.

**Comment by Daniel-KM** [comment]
You should rename the plugin folder "Stats".

**Comment by marcioyonamine** [comment]
I did it, but still not working.

**Comment by Daniel-KM** [comment]
Can you show me the full logs ?

**Comment by marcioyonamine** [comment]
hi daniel, i´m using an old release and it works!
