### ISSUE TITLE
Error on the home page after installing Stats plugin

### ISSUE THREAD

**Issue by hkaouri** [Daniel-KM/Omeka-plugin-Stats#16]
Hello,

i am getting the following error after installing Stats plugin on Omeka classic. Please help on how to fix this error.

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/aukoralh/public_html/plugins/Stats/models/Hit.php on line 563

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/aukoralh/public_html/plugins/Stats/views/helpers/Stats.php on line 432

**Comment by Daniel-KM** [comment]
Hi,
It works fine, but you use a too much recent version of php. 

On a production server, don't display deprecation messages.
