### ISSUE TITLE
Error 500 with huge files

### ISSUE THREAD

**Issue by symac** [Daniel-KM/Omeka-plugin-Stats#5]
Hello,
the plugin works fine when I use it for pictures but when I want to offer PDF files for download, it often crashes with an error in the logs saying: 
```PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 109365249 bytes) in /export/www/application/libraries/Zend/Controller/Response/Abstract.php on line 588, referer: http://1886.u-bordeaux-montaigne.fr/items/show/7403```

That seems to be because we send too many information using setBody [in DownloadController.php
](https://github.com/Daniel-KM/Stats/blob/master/controllers/DownloadController.php#L86). I have tried to fix it but still get errors. I have found that replacing:
```php
$file = file_get_contents($filepath);
$this->getResponse()->setBody($file);
```
by:
```php
$file = fopen($filepath,"rb");
		
set_time_limit(0);
while(!feof($file))
{
    ob_start();
    $content = fread($file, 1024*8*1024);
    print $content;
    ob_flush();
}
```

was fixing most of the issues but I still get errors and I am stucked there, can't think of another way of fixing this. Any idea welcome.

**Comment by Daniel-KM** [comment]
Comme cela corrige la majorité des problèmes, il faudra l'ajouter au code. Pour les fichiers plus gros, il faut voir si la modification du mode dans .htaccess suffit, voire s'il faut le mettre en option par défaut dans la config si cela corrige tous les gros problèmes.
